cors:
  originPatterns: http://localhost:3000,http://localhost:8080,https://erudio.com.br
file:
  upload-dir: /UploadDir
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rest_with_spring_boot_erudio
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
springdoc:
  pathsToMatch: 
  - /auth/**
  - /api/**/v1/**
  swagger-ui:
    use-root-path: true